### ISSUE TITLE
[Bug] DefaultRowSorter ClassCastException

### ISSUE THREAD

**Issue by CoreyD97** [nccgroup/LoggerPlusPlus#102]
I get this problem with the latest version of Logger++. Though I noticed if I install the 3.17 release from GitHub I could actually use the extension. On 3.18 it wouldn't work at all and the visual elements were a bit screwed up).

My terminal Burp log when using latest L++:
[log.txt](https://github.com/nccgroup/LoggerPlusPlus/files/4723194/log.txt)

After rolling back to 3.17
[log2.txt](https://github.com/nccgroup/LoggerPlusPlus/files/4723206/log2.txt)

I'm on Linux Mint, using:
`$ java -jar burpsuite_pro_v2020.4.jar`
Current extensions:
![image](https://user-images.githubusercontent.com/48349801/83636285-99fa7d00-a59d-11ea-9ae3-9f7f5c4ed09c.png)

Some details about my Java from Burp diagnostics if you need it:

java.runtime.name                Java(TM) SE Runtime Environment
java.runtime.version             10.0.2+13
java.specification.name          Java Platform API Specification
java.specification.vendor        Oracle Corporation
java.specification.version       10
java.vendor                      Oracle Corporation
java.vendor.url                  http://java.oracle.com/
java.vendor.url.bug              http://bugreport.java.com/bugreport/
java.vendor.version              18.3
java.version                     10.0.2
java.version.date                2018-07-17
java.vm.compressedOopsMode       Zero based
java.vm.info                     mixed mode
java.vm.name                     Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name       Java Virtual Machine Specification
java.vm.specification.vendor     Oracle Corporation
java.vm.specification.version    10
java.vm.vendor                   "Oracle Corporation"
java.vm.version                  10.0.2+13

_Originally posted by @Klambyyy in https://github.com/nccgroup/LoggerPlusPlus/issues/100#issuecomment-638163892_

**Comment by CoreyD97** [comment]
I've seen the issue you are experiencing once before, but only when I was using a particular version of Java, although the version you are using is not the same one. I'll investigate!

**Comment by CoreyD97** [comment]
Hi @Klambyyy,
Could you please try the version linked below?
I was able to reproduce the issue on the version on the BApp store, but do not seem to have the issue on this build.

https://github.com/nccgroup/LoggerPlusPlus/suites/682524522/artifacts/6318132

Thanks,
Corey

**Comment by Klambyyy** [comment]
@CoreyD97 Sorry for the delay - I tried your version, unfortunately the display still gets garbled when I select it:
![image](https://user-images.githubusercontent.com/48349801/84137950-6314e300-aa45-11ea-8c71-87a6aa5119da.png)


[log3.txt](https://github.com/nccgroup/LoggerPlusPlus/files/4751607/log3.txt)

**Comment by CoreyD97** [comment]
Hey, thanks for trying that!

I think I've identified the problem. When the table loads, it uses LogTableModel.getColumnClass() to determine the class of each column to enable it to sort the table properly when items are added. I was doing this by fetching the value of the first row of that column and just using that type, however in the case where the value was null I was defaulting to String. 

If the first value in a column had a null value and the rest were integers: sorting the table would attempt to compare the values in the column by casting them to String, which triggered this issue.
To fix this, if the value is null it'll now default to Object instead, so we shouldn't have casting issues in future, though I am unsure how this'll affect sorting.

If you could give this build a try and let me know how it goes, I'd greatly appreciate it!
https://github.com/nccgroup/LoggerPlusPlus/suites/775557964/artifacts/8133708

Thanks,
Corey
