### ISSUE TITLE
Base64 Encoding of HTTP Responses

### ISSUE THREAD

**Issue by C4H2O4** [nccgroup/LoggerPlusPlus#103]
Hello,

Processing saved log files when the HTTP response contains binary data can be a tedious task in common programming languages (I tested with Python and PowerShell) using the available parsers.

Would it be possible to encode the HTTP responses in Base64 to ease the parsing and analysis ?

Thank you very much for your help.

**Comment by CoreyD97** [comment]
Hey! Is this as an export option? If so I can definitely see this being useful for people and can whip this up!

**Comment by C4H2O4** [comment]
Hi!

Yes, it could definetly be an export option. 

Thank you very much for your feedback.

**Comment by CoreyD97** [comment]
If you were going to export multiple entries at once, how would you prefer them to be formatted? Would JSON be okay?

**Comment by C4H2O4** [comment]
In my particular case I'm using the CSV auto-export feature, so I would tend to prefer the CSV option.
JSON could work though.

I find the auto-csv export great because it allows me to test and have the results written automatically. It saves time when compared to the Json export that require the file to be manually generated multiple times. Maybe I should switch to the Elasticsearch back-end at some point.

**Comment by CoreyD97** [comment]
Ah I see, so an option to augment the CSV export to encode the request and response as Base64 instead would be more suitable. I can do that!

I've just written up manual export as Base64, so I'll add that anyway but I'll implement this too.

**Comment by C4H2O4** [comment]
That's awesome. Thank you !

**Comment by CoreyD97** [comment]
It took me a while to decide how I was going to implement this, but eventually realised that there's a pretty cool way I can add more things like this in future. 

Log Entries have a number of fields, and these are shared between the table, filters and exports. So by defining a new field like Request.AsBase64 or Response.AsBase64, they can be used by any of those functions. All I had to do was tell the LogEntry how to get that data and it works like magic :)

Thanks for helping me realise that with this issue. It'll make #104 super easy to implement as well!

![Screenshot from 2020-06-04 14-00-42](https://user-images.githubusercontent.com/1339555/83759748-f035f180-a66b-11ea-859d-5e1f62b14ca2.png)

If you want to test the functionality before it goes live the Jar built by Github Actions can be downloaded here: https://github.com/nccgroup/LoggerPlusPlus/suites/755195243/artifacts/7795343

**Comment by C4H2O4** [comment]
Amazing. Thank you very much for your prompt response and invaluable help ! I'm going to test it.
