### ISSUE TITLE
HTTP Response hash computation

### ISSUE THREAD

**Issue by C4H2O4** [nccgroup/LoggerPlusPlus#104]
Hello!

In order to quick-compare if binary data returned in the HTTP Response are equal, would it be possible to compute the SHA256 hashes of the responses and add them to the logs ?

Thank you very much for this great extension.

**Comment by CoreyD97** [comment]
Hey, does the hash need to be SHA-256 for any particular reason?
If its just for determining if the response is the same, I could use SHA-1 instead for a bit of a performance improvement? :)

**Comment by CoreyD97** [comment]
Hey! I've pushed the implementation for this and the build can be downloaded [here](https://github.com/nccgroup/LoggerPlusPlus/suites/960558635/artifacts/12073604) if you want to give it a try.

Thanks again for this suggestion!

**Comment by C4H2O4** [comment]
Thank you very much for these improvements!
