### ISSUE TITLE
CSV (auto-)export file selector with filetype guessed as JSON  

### ISSUE THREAD

**Issue by JulianVolodia** [nccgroup/LoggerPlusPlus#111]
**Description:**
When saving auto-export as CSV filetype on Kali is JSON but .csv extension added.

Don't know if it's some issue here. Needs more investigation and file why it not shows as previously (I remember that was not the problem time ago).

**Steps To Reproduce:**
On Logger++ tab click Auto-export as CSV. System dialog shows and files .json are only presented as filter by filetype is applied.
Could lead to overwrite of log if accidentaly file replacement confirmed.

**Expected behavior:**
See CSV files in catalogue to not overwrite it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1219023/88583488-9e4c8f00-d050-11ea-9247-26e9de957725.png)

**Version:**
3.18

**Comment by CoreyD97** [comment]
Thanks, is this just a ui issue? Or does it actually save it as json?

**Comment by JulianVolodia** [comment]
For me it's strange and if you want you could makr me as assigned, because we needs more info (aka testing on other setup).
Imho some caller of fs selector handler should filter on CSV files not JSON as now. 

Sorry for filing not complete, but won't forget about it.

**Comment by JulianVolodia** [comment]
On right you see files, on left not. I remember that it was displayed with this file selector properly, and don't know more about nature of issue. Might be some Gnome / Kali problem. Will return to this in one week. Thanks.

![image](https://user-images.githubusercontent.com/1219023/88585136-fab0ae00-d052-11ea-9c1e-d860fd881caa.png)

**Comment by CoreyD97** [comment]
I think this is just due to the file selector being configured incorrectly and shouldn't actually export json so should be an easy fix.

**Comment by JulianVolodia** [comment]
Looks like it will be fixed after PR#115 gets merged.
