### ISSUE TITLE
There are errors in the display of UI in my PC

### ISSUE THREAD

**Issue by ThoundsN** [nccgroup/LoggerPlusPlus#112]
Please see the attached video, I don't know how to describe it.

3,18 Latest version of logger++, I have no ideas why this happens.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28804535/89620676-93042980-d8c2-11ea-86ea-5374086bfddb.gif)

**Comment by CoreyD97** [comment]
Hi @ThoundsN,

Please could you confirm that you are using the latest version? 3.18 is the latest, however you seem to have an "About" page in Logger++ that suggests an older version of the extension.

You can get the latest version from the BApp store, or use the experimental 3.19 version available from [here](https://github.com/nccgroup/LoggerPlusPlus/suites/968881771/artifacts/12269298).

Thanks!

**Comment by ThoundsN** [comment]
Yeah, I am using the 3.18 then I got the error, so I switched to the 3.16 older version, but there are still errors, and the errors are not stable, sometime it happens sometimes not. So really don't know what caused it, sometimes reinstall the extension helps.

Thanks for your help and reply!

**Comment by CoreyD97** [comment]
This should be fixed in the latest versions of the extension, could you please try the experimental version I linked above?

Thanks!
