### ISSUE TITLE
Add Development section to README

### ISSUE THREAD

**Issue by latacora-tomekr** [nccgroup/LoggerPlusPlus#113]
**Feature description:**
I want a Development section added to the README for the recommended process for developing, debugging, and testing the extension.

**Scenario example:**
This would make it easier for new-comers to the project to contribute features

**Comment by CoreyD97** [comment]
Thank you for the suggestion.
There are a number of useful tips that aid in debugging Burp Extensions, so I'll be sure to add these to make it easier to contribute in future :)
