### ISSUE TITLE
UTF-8 characters not working in Color filters

### ISSUE THREAD

**Issue by Hipapheralkus** [nccgroup/LoggerPlusPlus#118]
**Description:**
When response contains some Czech (or other UTF-8 characters), the filter can't be created.

**Steps To Reproduce:**
Copy paste this Color filter:
 `Response.Body CONTAINS "Z důvodu"`
 `Response.Body CONTAINS "Z části"`

**Expected behavior:**
It will work and color-highlights all responses containing this static text.

**Screenshots:**
![image](https://user-images.githubusercontent.com/4717664/93790216-14c1d380-fc33-11ea-8175-790b3cc5e91d.png)
![image](https://user-images.githubusercontent.com/4717664/93790531-71bd8980-fc33-11ea-9b6b-586be063756f.png)

**Version:**
3.18

**Comment by CoreyD97** [comment]
Just pushed a fix for this issue now, though the unicode characters will be converted to their `\u` equivalents when displayed in the log field. I'll look at ways to avoid this in future.

e.g. `Response.Body CONTAINS "Z \u010D\u00E1sti"`
