### ISSUE TITLE
v3.18 - Bug:  java.lang.IllegalStateException 

### ISSUE THREAD

**Issue by xnlcode** [nccgroup/LoggerPlusPlus#119]
**Description:**
I am running Burp Suite Pro, and because of the text being blurry, I run as a shortcut using the following:
"C:\Program Files\Common Files\Oracle\Java\javapath\java.exe" -Dsun.java2d.uiScale=1 -jar "C:\Program Files\BurpSuitePro\burpsuite_pro.jar"
This opens a command window, and then Burp Suite.
Everything seems to work as usual, but in the command window I start seeing the following error getting logged a number of times, every time I have Burp open:

java.lang.IllegalStateException                                                                                                                                     at java.base/java.util.concurrent.ConcurrentHashMap$BaseIterator.remove(ConcurrentHashMap.java:3444)                                                        at com.nccgroup.loggerplusplus.logview.processor.LogProcessor$AbandonedRequestCleanupRunnable.run(LogProcessor.java:350)                                    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)                                                                        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)                                                                               at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)                                 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)                                                                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)                                                                at java.base/java.lang.Thread.run(Thread.java:832) 

I don't know what triggers this, and I don't know if there are any adverse affects to this, but I wanted to report it anyway just in case it's an issue you want to look into.

**Steps To Reproduce:**
I do not know how to specifically reproduce this, but just happens while I have Burp open and use it for a while.

**Expected behavior:**

**Screenshots:**

**Version:**
Burp Suite Pro v2020.9.2 Build 4265
Logger++ v3.18

**Comment by CoreyD97** [comment]
Thank you for the report.

I believe this should be fixed in the version available from the repository, but it hasn't been pushed to the BApp store as of yet. Hoping to get it updated soon.
