### ISSUE TITLE
Filter text invisible after syntax error

### ISSUE THREAD

**Issue by ldionmarcil** [nccgroup/LoggerPlusPlus#125]
**Description:** After triggering a syntax error from the filter textarea, a pop up shows up. Once this pop up is closed the text in the filter area becomes invisible, if using Light mode. To fix it, we need to reload the extension.

**Steps To Reproduce:** 
1. Use Light mode
2. Type an incorrect filter
3. Close the pop up
4. Notice the textarea text being invisible

**Expected behavior:** Filter text is visible

**Screenshots:**
![image](https://user-images.githubusercontent.com/1320868/107810865-54e93600-6d3b-11eb-8fa4-8eb951697cfc.png)
![image](https://user-images.githubusercontent.com/1320868/107810879-587cbd00-6d3b-11eb-8eae-5c4b3bd90439.png)

**Version:**
Bapp Store version. 
Tested on Burp 2021.2 and 2020.11.3.

**Comment by CoreyD97** [comment]
I've recently removed the coloring on filter texts to prevent incompatibilities with custom themes, so this issue should be resolved in the next release. Let me know if you still have issues after this.
