### ISSUE TITLE
Accessing remote Elasticsearch instance using basic auth credentials

### ISSUE THREAD

**Issue by Regala** [nccgroup/LoggerPlusPlus#128]
**Description:**
Most modern ES instances use basic auth credentials, with the possibility of additional ACL. It seems Logger++ doesn't allow the basic auth schema to be passed in the hostname. Is this something we could fix? 

**Steps To Reproduce:**

So if we try to use `admin:password@elasticsearch.com` as hostname:
<img width="433" alt="logger" src="https://user-images.githubusercontent.com/1380527/115997124-dd0c7700-a5d9-11eb-876a-b55dcfb5dbe0.png">

Leads to:
<img width="549" alt="logger_2" src="https://user-images.githubusercontent.com/1380527/115996980-55bf0380-a5d9-11eb-9573-9ee4c5951ed8.png">

**Expected behavior:**

The parser should accept this as a valid URL.

**Version:**

3.19

Thanks!

**Comment by Regala** [comment]
Ok seems like maybe this isn't that trivial to do; you're correctly using the high level REST API which already sets the basic auth header. So this ends up being an edge case, when the server only accepts the basic auth creds in the URL 🤦‍♂️ (e.g. Aiven). From my limited knowledge and some minutes of research I couldn't actually figure out how to pass a custom URL since `HttpHost` doesn't allow to set that. If I figure out something I'll post here, but will prob need some help 😬

**Comment by CoreyD97** [comment]
Sorry for the delay. I'll look into this soon.

**Comment by Regala** [comment]
Thanks!

As a workaround, I set up a local reverse proxy that automatically adds the require Authorization header. Works, but it's not too fancy.

**Comment by CoreyD97** [comment]
Turns out ElasticSearch uses a different `Authorization` header value for basic auth vs API keys. I've added a dropdown option to let you select which one to be used. Let me know if you have any problems.

**Comment by Regala** [comment]
This is super weird but seems that by default it still requires the basic auth creds to be passed in the URL, and discards the Authorization header 🤦‍♂️

I was trying to do `RestClientBuilder builder = RestClient.builder("https://user:pass@host:443)` (since it accepts a URI as string) but this throws a nodename not known; trying to dig on it since it should work imo.

**Comment by Regala** [comment]
@CoreyD97 do you remember the setup you used to test this?

**Comment by CoreyD97** [comment]
@Regala - I used https://github.com/deviantony/docker-elk to reproduce this with the username: elastic and password: changeme

**Comment by Regala** [comment]
OK so regarding this, I just cloned the repo and did `docker-compose up` and ES is running:
![image](https://user-images.githubusercontent.com/1380527/118115660-24b83e80-b3e1-11eb-8c47-83570e72d5f4.png)

Changed the settings to:
![elastic_1](https://user-images.githubusercontent.com/1380527/118115692-313c9700-b3e1-11eb-8c95-feb7396cb388.png)

But still getting:
![elastic_2](https://user-images.githubusercontent.com/1380527/118115714-38fc3b80-b3e1-11eb-8176-6115ffe4a3f8.png)

Can't help but notice that after this, if you try to configure again immediately after the menu shows/reverts to ApiKey:
![image](https://user-images.githubusercontent.com/1380527/118115806-55987380-b3e1-11eb-8792-65536a2e9a16.png)

I'm trying to proxy the Java requests through Burp itself to see what's happening but without luck, I'll see if I can do it other way 🙈

**Comment by CoreyD97** [comment]
For the auth type issue, I fixed this last night but that commit was before the release I sent over :) https://github.com/nccgroup/LoggerPlusPlus/commit/b94759e6cf2c20bd86f4e0f50df11bbf1e418784

Can you confirm if this command works for you?
```curl  "http://127.0.0.1:9200/_cat/shards" -H 'Content-Type: application/json' -H "Authorization: basic `echo -n "elastic:changeme" | base64`"```

**Comment by Regala** [comment]
Oooh alright 😊

Yep can confirm it works:
![image](https://user-images.githubusercontent.com/1380527/118129056-9b5e3780-b3f3-11eb-82dc-4f8b49a58df8.png)

**Comment by Regala** [comment]
OK! b94759e works! Built from downloading the .zip at https://github.com/nccgroup/LoggerPlusPlus/tree/b94759e6cf2c20bd86f4e0f50df11bbf1e418784 and not only the  configuration menu persists but it also connects to ES 😍 

But for some reason I just cloned the repo again on master and built it and doesn't work (it didn't merge?); or maybe I'm just doing it something wrong, but it's weird.

**Comment by CoreyD97** [comment]
Glad you confirmed that! I'm afk at the moment but will get the fixes for the exception merged in and do another proper build and see if we can get it working properly.

I started working on #107 last night also, so hopefully that'll be useful for you too 😁

**Comment by Regala** [comment]
Will check it out!!
