### ISSUE TITLE
Can't use Logger++ together with Param Miner

### ISSUE THREAD

**Issue by cokeBeer** [nccgroup/LoggerPlusPlus#132]
**Description:**
 I tried to obeserve the http requests of ParamMiner, but the view of Logger++ seems not work
**Steps To Reproduce:**
open ParamMiner
open Logger++
use ParamMiner
Click the view of Logger++
**Expected behavior:**
burp's view get wrong
and logger++'s view can't be open

**Screenshots:**
![image](https://user-images.githubusercontent.com/70683161/118215825-e8e6ad00-b4a4-11eb-976d-2d92ea32a1d0.png)
![image](https://user-images.githubusercontent.com/70683161/118215896-0ca9f300-b4a5-11eb-948b-a9f5801e1df4.png)

**Version:**
Logger++ 3.1.8
ParamMiner 1.2.8

**Comment by CoreyD97** [comment]
Are you still having this issue? I've been unable to reproduce this in my tests.

**Comment by CoreyD97** [comment]
Stale. Does not appear to be reproducible.
