### ISSUE TITLE
getting classnotfound exception

### ISSUE THREAD

**Issue by bharathyakasi** [nccgroup/LoggerPlusPlus#137]
Hi, i downloaded the code and imported in eclipse and compiled . i exported it as runnable jar and try to add in burp extensions i am getting classnotfound exception.

**Expected behavior:**

![image](https://user-images.githubusercontent.com/49576530/122172195-25d80200-ce9e-11eb-8933-0d938f41402e.png)

**Version:**

**Comment by CoreyD97** [comment]
It looks like when you've built the jar, it hasn't included the required dependencies. 
Can you confirm how you built the jar?

**Comment by bharathyakasi** [comment]
I used Eclipse IDE and Java 1.8:
Imported the project from github and compiled 
![image](https://user-images.githubusercontent.com/49576530/123262590-aa1d2b80-d515-11eb-87d2-56fef9cd8fa3.png)

**Comment by bharathyakasi** [comment]
![image](https://user-images.githubusercontent.com/49576530/123262957-1730c100-d516-11eb-8564-1720d38a6e3e.png)

**Comment by CoreyD97** [comment]
Logger++ requires a number of libraries to run, which are not included if the jar is built normally. Instead, you'll need to use the `gradle jar` command to build the project, as this includes the required libraries into the generated jar file.
