### ISSUE TITLE
Unable to open exported har file in fiddler or other har file viewers.

### ISSUE THREAD

**Issue by aloknag** [nccgroup/LoggerPlusPlus#138]
I cloned the repo and build the jar, imported that jar into burpsuite (build:1927). I had a few requests filterd in Burp proxy history which I imported to logger.
I then selected a few of them and did same as har.
I also tried export as har from options menu.
Unfortunately, when I tried opening the har file in either fiddler or chrome extn for har viewer, it shows no requests.
Opening har in chrome network give console error:
`Failed to load HAR file with following error: SyntaxError: Unexpected end of JSON input`

**Steps To Reproduce:**
1. Build and import latest har.
2. Add a URL in Burp Scope.
3. Enable Intercept. send a req and change it on fly.
4. Now you see the req in Burp Proxy Http history.
5. Select the req and do export as Har.
6. Additionally you can try to import  burp history to logger++ and click export as har in options.

**Expected behavior:**
Exported har file should open in any har viewers. ex. fiddler

**Version:**
master

**Comment by aloknag** [comment]
Opening the har in sublime text show only following line
`{"log":{"version":"1.2","creator":{"name":"LoggerPlusPlus","version":"3.19.1"},"entries":[{"startedDateTime":"1970-01-01T05:30:00.000+0530"`

**Comment by CoreyD97** [comment]
Seems like there must be a null pointer when it tries to calculate the start/end time. Can you download this release and let me know if this fixes things?

https://github.com/nccgroup/LoggerPlusPlus/suites/3078430014/artifacts/70206328

Thanks!
