### ISSUE TITLE
SameSite attribute filter

### ISSUE THREAD

**Issue by amammad** [nccgroup/LoggerPlusPlus#140]
**Feature description:**
I want to find and coloring the responses with SameSite attribute in their cookies header but I can't do this.
for example add this filter : `Response.Cookies CONTAINS "SameSite"`
Or more fantastic : `Response.Cookies.Samesite IN ["none","Lax"]`
If there is any way except use grep to solve my problem, please help me or add this feature in your great Extension.
tanks so much my dears.

**Comment by CoreyD97** [comment]
This is a good enhancement idea, thanks.
The issue you're unable to achieve this with the `Response.Cookies CONTAINS "SameSite"` filter is the `Response.Cookies` object only stores the cookie name for now. Until this feature is implemented, you can use the following filter.

`Response.headers == /Set\-Cookie:[^\n]*?SameSite=/`

**Comment by amammad** [comment]
Yah, tank so much dear Corey,
just now I added some more colors to my view logs :)
