### ISSUE TITLE
Cannot add comment 

### ISSUE THREAD

**Issue by DidierA** [nccgroup/LoggerPlusPlus#145]
**Description:**
I cannot add content in the 'Comment' column in Logger++. When I double click in the comment field of one line, it becomes editable, I can type my content, but cannot validate. If I press enter or click anywhere else, the field remains in edition mode, and the contents is not validated. The only way to get out is by pressing escape. A stackstrace is dumped on the error log when pressing enter, stating 'Data is read only'. I have attached the stacktrace.
[loggerplusplus-stacktrace.txt](https://github.com/nccgroup/LoggerPlusPlus/files/7208720/loggerplusplus-stacktrace.txt)
 
I don't know if it's relevant, but I also noticed that when Logger++ is active, the comment field in Logger (the one integrated to burp) is filled with entries starting with `$LPP:` such as  `$LPP:23:6663a343-49cb-4aa9-8ac8-05eef16c6ef5$`

**Steps To Reproduce:**
Go to Logger++ Tab, click on the comment field on any line, enter contents and press enter.

**Expected behavior:**
The contents should be added to the comment column.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1620015/134303372-0cbcb5f4-ba88-408d-ad86-a0bf67ff637b.png)

**Version:**
3.19.2, updated august 6 in Bapp store <=> 3.18 here

**Comment by ngregoire** [comment]
Same here: I can't set comments in L++. But no stack-trace on my side...

**Comment by CoreyD97** [comment]
Sorry this took so long to get to, despite being such a simple fix. 

The root cause here was switching to a different IHttpRequestResponse type, designed for persistent storage. This was done in the hopes to decrease memory usage, but seems to make the data read only. 

I'll be pushing a new release for this shortly.
