### ISSUE TITLE
[Question] Restore logs after Burp closes

### ISSUE THREAD

**Issue by ioasdjiojqiwojaosncasoidjqoiwjeon** [nccgroup/LoggerPlusPlus#148]
Is there a way to restore all logs in Logger++ after Burp is closed? I know that I can import the logs from the Burp's Proxy History, the thing is that I want to have an exact copy of the last logs captured by Logger++ which includes logs from Repeater,Intruder,Extender,etc.

**Comment by AkikoOrenji** [comment]
See https://github.com/nccgroup/LoggerPlusPlus/issues/133

**Comment by CoreyD97** [comment]
Duplicate of #133
