### ISSUE TITLE
Could we add filter for listener

### ISSUE THREAD

**Issue by WhiteBearVN** [nccgroup/LoggerPlusPlus#163]
**Feature description:**
Hi team, 

I hope we could add filter by listener port in Logger++ It's help people want to use a lot of connections in one burpsuite like me.

For example: 

I use mobile A at port 3128 and mobile B at port 3129, currently, I use 2 windows of burpsuite but it's really hard to compare and filter. I wish I could see all requests in one burpsuite and can make 2 different colors for 2 listeners. It's will be super cool.

Thank you.

**Comment by CoreyD97** [comment]
Duplicate of #109
