### ISSUE TITLE
Cursor changes position upon new requests coming in

### ISSUE THREAD

**Issue by ldionmarcil** [nccgroup/LoggerPlusPlus#164]
Using the Master branch, Logger++ will have the request pane move its cursor back to the first position of the current request when new requests come in. As a result, it's impossible to scroll a request as long as new requests are coming in. Video shown below:

https://user-images.githubusercontent.com/1320868/203618469-6f1652a7-7cc9-4ed8-b814-d72780cd5e7a.mp4

**Comment by tsc-awardle** [comment]
I also had this issue. It also affected the ability to use the search/highlight functionality.

Fixed in my PR #165

**Comment by CoreyD97** [comment]
PR merged into master
