### ISSUE TITLE
Repeater messages never get a response in LPP view

### ISSUE THREAD

**Issue by tsc-awardle** [nccgroup/LoggerPlusPlus#166]
**Description:**
Repeater requests always show up as incomplete in LPP, but the response is never added. LPP eventually marks them with a "Timed Out" comment.

**Steps To Reproduce:**
Send repeater request and observer Logger++ view.

**Expected behavior:**
Logger++ should update repeater request logs with the response when it arrives

**Screenshots:**

**Version:**
Current master branch 92530b5b8c16b87c05ddfda9052dec3896fc821b

I am submitting a PR for this fix now.

**Comment by CoreyD97** [comment]
As mentioned in the PR close, it appears that recent changes to the Burp Suite API have broken the request + response matching method previously being used. PR #172 will revert back to the comment tagging method until something better can be found.
