### ISSUE TITLE
Loading logger++ leads to burp hanging

### ISSUE THREAD

**Issue by tmgbiswadp** [nccgroup/LoggerPlusPlus#174]
**Description:**
Loading logger++ results in burp hanging

**Steps To Reproduce:**

+ Don't know the specific way to reproduce the issue but disabling extensions on start of burp.

![image](https://user-images.githubusercontent.com/37303430/221646035-6b7c0663-d8eb-4b82-800a-2af36ad91eab.png)

 + Loading logger++ after burp has opened the project results in burp freezing.

![image](https://user-images.githubusercontent.com/37303430/221646373-5de702dd-fcce-4569-9d25-432fc8e1c271.png)

![image](https://user-images.githubusercontent.com/37303430/221647202-1598d0ef-79aa-4a8c-95c9-39d7fbdf043c.png)

**Screenshots:**

![image](https://user-images.githubusercontent.com/37303430/221645116-a7765a78-eecf-4e22-9aa5-5b5a27960d89.png)

**Version:**
3.19.4

**Comment by CoreyD97** [comment]
Can you confirm what version of Burp you're running? I've seen this error a few times on earlier Burp versions.

**Comment by tmgbiswadp** [comment]
I am using burp 2022.8.5. Here is full output.

[err.txt](https://github.com/nccgroup/LoggerPlusPlus/files/10843293/err.txt)

**Comment by CoreyD97** [comment]
Please try using the latest version of Burp and let me know if the issue persists.

**Comment by tmgbiswadp** [comment]
Starting burp in half window seems to solve it.
