### ISSUE TITLE
Populate a "View logs" column from a regex

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/LoggerPlusPlus#175]
**Feature description:**
I want to get an old feature back: being able to populate a "View logs" column from a regex, as described [here](https://twitter.com/MasteringBurp/status/1630945655483932673)

**Scenario example:**
This would allow to extract data in a way similar to Intruder's Grep Extract

**Similar issue:**
Issue #153 looks similar

**Comment by C0DEbrained** [comment]
Duplicate of #153. Will track there :)
