### ISSUE TITLE
EasyFilter

### ISSUE THREAD

**Issue by create32** [nccgroup/LoggerPlusPlus#176]
**Feature description:**
Every time I apply a filter, I have to look up the help page. 
I hope that I could just choose a filter just by clicking like the below picture. 

**Scenario example:**
* Easy Filter
![image](https://user-images.githubusercontent.com/21360469/231363905-c54c6a9c-c237-481b-8110-40704a735e7e.png)

![image](https://user-images.githubusercontent.com/21360469/231363154-f157b920-87c6-48ce-9f4c-bb6a8e670a56.png)

* UI suggestion
![image](https://user-images.githubusercontent.com/21360469/231363716-48a14659-f58d-49a6-a61b-bc6bf661d767.png)

**Comment by CoreyD97** [comment]
Thanks for the suggestion. 

Unfortunately whilst writing filters may take a little getting used to, I don't think I will prioritize this unless there is more demand from other users. Writing filters was designed to be as natural as possible, and can be written very quickly for most cases. You can also create a new filter and add to your existing filter by right clicking elements in the table.

Is there something in particular that you're struggling with that I could clarify or simplify in some way?
