### ISSUE TITLE
What's the latest EasticSearch Remote version,  loggerPlusPlus is Compatible with?

### ISSUE THREAD

**Issue by priyanshuxo** [nccgroup/LoggerPlusPlus#177]
Hi , I am enjoying this tool very much in BURP . I would like to log all proxy in remote elasticsearch instance , but currently it is not logging  any data with the latest elastic version 8.*.*. Can anyone tell me the latest version loggerPlusPlus is compatible with.

**Comment by CoreyD97** [comment]
Glad to hear you're enjoying it. The current ElasticSearch dependency is 7.5, but I will look to update this when I next work on the tool.

**Comment by priyanshuxo** [comment]
Thank you for your response. Thumbs Up for all your work on this tool !!
