### ISSUE TITLE
Add filter for Project Scope settings

### ISSUE THREAD

**Issue by M-Davies** [nccgroup/LoggerPlusPlus#189]
**Feature description:**
I would like a filter field that would limit the logs displayed to those that are in the user defined scope within burp's project settings:
![image](https://github.com/nccgroup/LoggerPlusPlus/assets/25231953/3c8800f0-fa50-4482-85d3-bef6c34d74e0)

**Scenario example:**
This would significantly shorten the filters I use, making them more readable and allow for existing burp projects to be easily setup with Logger++ on installation

**Comment by C0DEbrained** [comment]
Hey! I believe `Entry.InScope` is what you're looking for.

I the current release the title of the table column is incorrect, but it still functions properly.

**Comment by M-Davies** [comment]
If it does exist, it doesn't appear to be in the documentation. Which is why I asked :) 

https://github.com/nccgroup/LoggerPlusPlus/wiki/Filter-Fields

**Comment by C0DEbrained** [comment]
Ah! That documentation is extremely old. I'll get that updated.

If you need help with filters, check out the built in help tab :)

**Comment by M-Davies** [comment]
Thanks Corey. I've found that documentation now but it would ideal if it was in the wiki too as I'm sure a lot of people (me included) tend to gravitate towards wikis and markdown files for documentation prior to looking through the tabs in burp
