### ISSUE TITLE
No custom options

### ISSUE THREAD

**Issue by f4cknet** [nccgroup/LoggerPlusPlus#192]
Burpsuite：2023.8
Logger++：3.20
![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/e99d4f18-455b-4268-8b4c-5970cd9a8c99)
As shown in the above figure, this version does not have customizable configuration options.Where can I configure Elasticsearch？

**Comment by C0DEbrained** [comment]
That looks to be the built in Logger tool, try reloading the Logger++ extension and see if the tab appears.

**Comment by f4cknet** [comment]
I have installed Elastic version 8.0.1 using Docker and set xpack. security. enabled=false and xpack. security. http. ssl. enable=false. I have configured Elastic addresses in Logger++, but cannot upload Logger logs to Elastic. Is the version incompatible?
`docker run --name elasticsearch --net elastic  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e xpack.security.enabled=false -e xpack.security.http.ssl.enable=false -t docker.elastic.co/elasticsearch/elasticsearch:8.0.1`

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/5a82d8f9-7db8-451f-b0be-e1b88f53037b)

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/4c5e3907-26f7-4941-b889-c49b22cd9879)

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/295ed5f0-9a2a-4bde-9063-2ea94e1817f5)

**Comment by f4cknet** [comment]
I have seen your es version is 8.6.2 with co.elastic.clients:elasticsearch-java:8.6.2. so I uninstall 8.0 es, and install 8.6.2,but it still upload data to es failed
![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/fc3ee0c0-10c1-4325-9124-9d0c006da358)

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/e06a9928-51f9-43b1-aa91-e7bd98500d50)

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/12128859/b1583603-437a-4161-b182-ed648520879c)

**Comment by C0DEbrained** [comment]
There's a bug in the current version that prevents the Elastic exporter from working. Upgrades to the exporter are being tracked in #157.
