### ISSUE TITLE
send request  from logger++ to an extensions

### ISSUE THREAD

**Issue by abdulsec** [nccgroup/LoggerPlusPlus#193]
**Feature description:**
I want send request  from logger++ to an extensions

**Scenario example**
 it will make easy  to send  an js file to an extensions that can generate  wordlist

**Comment by C0DEbrained** [comment]
Unfortunately, this isn't possible in the Logger++ table, but if you select a request and right click the request's contents in the request viewer, all the expected context menu options from other extensions will be available.
