### ISSUE TITLE
Import from ZAP proxy does not work

### ISSUE THREAD

**Issue by ciapatakoza** [nccgroup/LoggerPlusPlus#198]
**Description:**
Import from latest Zap proxy does not work, I am getting `importZAP: Wrong Path Format` exception and no packets imported.

**Steps To Reproduce:**
Use latest Zap proxy to collect some requests, then use `Export Messages to File...` then try to import logs to logger++.
Exception in extension console will occur.

**Expected behavior:**
Imported log entries

**Screenshots:**

**Version:**
3.20.0

**Comment by ciapatakoza** [comment]
Actually pulled the latest pre-relase version of the extension and there is no exception in the log, but also no logs imported.

**Comment by ciapatakoza** [comment]
Ok, seems that develop branch fixed that already. Using now custom build from develop branch, any chance to get that pushed to main branch and released as 3.20.1?

**Comment by C0DEbrained** [comment]
Thanks for the report. I'm not sure what caused this but glad to hear its fixed in the dev branch. I'll be looking to get that merged soon.
