### ISSUE TITLE
response time error causing packet display timeout

### ISSUE THREAD

**Issue by sp4rkw** [nccgroup/LoggerPlusPlus#201]
**Description:**
When I use the plugin, I found that some of the packets show incomplete and its return packet is empty, but it's normal in burp's http history.
These packets showing incomplete have a common feature, a response time of 1970. hopefully this will help troubleshoot the problem.

**Screenshots:**
![image](https://github.com/nccgroup/LoggerPlusPlus/assets/33112152/0c8f90ce-7380-471b-8e68-8db563bcbb34)

**Version:**
matster

**Comment by ngregoire** [comment]
I think I hit the same bug... Using Logger++ 3.20.0 and Burp Suite Pro EA 2023.11.1.2, all the Proxy Traffic appears in "View Logs" with no response, even if it looks fine in Proxy History. 

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/4039324/02af5fbc-b91a-4926-8a81-b8c48219e4db)

**Comment by ngregoire** [comment]
I downgraded to 3.19.4 and I see the same behavior, but for all tools (not only Proxy). So it may be that the bug has been partially fixed in 3.20.0

**Comment by C0DEbrained** [comment]
I couldn't reproduce this in my tests, please can you try the latest release and let me know if you're still having this issue?

**Comment by ngregoire** [comment]
I tried with v3.20.1 and managed to reproduce the bug.

However, the problem disappeared after I fully reset my setup:
- Menu bar > Burp > User settings > Restore defaults
- Menu bar > Project > Project settings > Restore defaults > All
- Logger++ > Options > Reset All Settings

**Comment by c1phy** [comment]
I have the exact same issue (3.20.0 with Burp 2023.12.1.5) when I set the "Options" > "Log From" to "All Tools" and nothing else ticked. Every requests ends in 1970.
When I enable "Proxy" and then "All Tools" it works again.
Really odd.

**Comment by sp4rkw** [comment]
> I tried with v3.20.1 and managed to reproduce the bug.
> 
> However, the problem disappeared after I fully reset my setup:
> 
> * Menu bar > Burp > User settings > Restore defaults
> * Menu bar > Project > Project settings > Restore defaults > All
> * Logger++ > Options > Reset All Settings

These operations are useful，Thanks
