### ISSUE TITLE
"Grep Values" doesn't work in 3.20.0 (no matches)

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/LoggerPlusPlus#203]
**Description:**

Whatever the regexps used in "Grep Values", they are never matched

**Steps To Reproduce:**

1) Log some traffic in "View Logs"
2) Switch to "Grep Values"
3) Enter a basic regexp like `(Powered-By|Server): (.+)`, check "Search responses" and click on "Search"
4) No values are extracted

**Expected behavior:**

The "Results" and "Unique Results" tables should be populated

**Version:**

v3.20.0: regexp isn't matched, tabs aren't populated
v3.19.4: response bodies are empty (cf issue #201)
v3.18: works fine

**Comment by C0DEbrained** [comment]
Thanks for the report.

Please could you try this on [v3.20.1](https://github.com/nccgroup/LoggerPlusPlus/releases/tag/v3.20.1) and let me know if you still have this issue? I wasn't able to reproduce on v3.20.0, so I'm hoping I solved your issue but can't be sure.

![image](https://github.com/nccgroup/LoggerPlusPlus/assets/1339555/372b9f1c-513d-416b-a200-b4f5f9321daa)

**Comment by ngregoire** [comment]
I can't reproduce the bug on v3.20.1, so I'll close this issue.
