### ISSUE TITLE
Malformed Elastic Exporter Address

### ISSUE THREAD

**Issue by MrTuxracer** [nccgroup/LoggerPlusPlus#208]
**Description:**
When setting the address in the Elastic Exporter Configuration, the value somehow gets mangled to a string like `HTTPS://192.168.1.1/192.168.1.1:9200/logger` where `192.168.1.1` is the `address` value.

**Steps To Reproduce:**
- Start a fresh Burp Project and install Logger++ either through the Bapp store or directly from this repo
- Configure the Elastic Exporter and set the `Address` to any value
- Start the Elastic Exporter, which will get you a log output in the extension's output pane of `Starting ElasticSearch exporter. HTTPS://192.168.1.1/192.168.1.1:9200/logger`

**Expected behavior:**
It looks like the `address` value is somehow used twice when constructing the Elastic URL, but it should only be there once.

**Version:**
Tested on the following clean/fresh Burp combinations (all have the same problem):
- Burp Suite Pro 2024.3.1-28157 (Early Adopter) on MacOS (ARM) with Logger++ v3.20.0 and v3.20.1
- Burp Suite Pro 2024.2.1.3 on MacOS (ARM) with Logger++ v3.20.0 and v3.20.1
- Burp Suite Pro 2024.2.1.3 on Linux (x86) with Logger++ v3.20.0 and v3.20.1

**Comment by C0DEbrained** [comment]
Thanks again for the report.

Just double checking, does the exporter start up okay after displaying this message? Looks like the HttpHost object is created as expected but the log message might just be incorrect since it's being constructed manually.

https://github.com/nccgroup/LoggerPlusPlus/blob/master/src%2Fmain%2Fjava%2Fcom%2Fnccgroup%2Floggerplusplus%2Fexports%2FElasticExporter.java#L122-L123

**Comment by MrTuxracer** [comment]
While debugging, I realized that my Java had an old ES certificate added, which seems to be the reason why Logger++ always gets stuck when connecting to my ES cluster. So that log output was just misleading my debugging, and the feature is still working as expected. 

Thanks again for double-checking! Very much appreciated!
