### ISSUE TITLE
Send logs to an external host

### ISSUE THREAD

**Issue by MadDud** [nccgroup/LoggerPlusPlus#62]
Awesome plugin. 
Besides ElasticSearch it would be great to have an option to also send logs to Splunk. Would it be possible to add a feature to just send events anywhere over HTTP (with JSON in POST request). or via syslog?

**Comment by CoreyD97** [comment]
Thanks! I agree this would be useful. 
I'm trying to think of how best this would be implemented, especially if the post request would require additional cookies or headers to authenticate with the remote server.

Would allowing you to specify a template request to have the data inserted into before being submitted be an acceptable solution?

e.g

```
POST /endpoint
Host: example.com
Connection: close

{
client: "ABCDE", 
data:{{LPPDATA}},
authkey: "KEY"
}
```

The extension could then replace the {{LPPDATA}} token with the actual data in JSON format. This would be useful in case people wanted to wrap the data with other information.

**Comment by MadDud** [comment]
@CoreyD97 I see your point. This indeed is a bit more complicated than just having a field for a URL.
For me the text area with a template would be fully sufficient, and I guess that most people using Burp would understand too, how it works. 

Maybe you would be able to simply re-use the editor from repeater, which has got nice handling of headers etc?

**Comment by CoreyD97** [comment]
Great idea, thank you!

I'll take a look at getting this implemented soon. 🙂

**Comment by CoreyD97** [comment]
Unfortunately with the addition of ElasticSearch support I don't see this feature being used enough to implement, though if more people want this in future it is something I could work on.
