### ISSUE TITLE
Use the ElasticSearch high-level REST client

### ISSUE THREAD

**Issue by UnicodingUnicorn** [nccgroup/LoggerPlusPlus#73]
The Java client currently used in Logger++ is deprecated as of ElasticSearch 7.0.0 and will be removed in 8.0.0. It has been recommended by the docs to update any uses of the library to use the high-level REST client.

**Comment by CoreyD97** [comment]
Hey, thanks for the heads up on this. I've already updated the extension to use the high-level REST client in the development branch but am working out a couple of issues with other areas of functionality before release 😃
