### ISSUE TITLE
[Feature] Allow multi-selection. (with some Contextual Menu additions)

### ISSUE THREAD

**Issue by Shaddy** [nccgroup/LoggerPlusPlus#75]
Hi :),

It would be great to be able to select multiple requests in the JTable and add more contextual actions to them. 

I would add a selection by using the first element and last element together along with Mayus key or to be able to select individual items with CTRL and left-click.

Current menu actions:

![image](https://user-images.githubusercontent.com/247221/63016470-092ea580-be94-11e9-81f5-d7a6be37e9b7.png)

Examples:

- Copy selected URLs.
- Copy selected URLs (Remove duplicates).
- Copy selected query params.
- Send to "Extension" (e.g. Stepper)
- Colorize selected items (Can this be done using indexes? Or it will generate problems when the Logger reaches his limit?)

Probably there could be more but I find these interesting to mention.

Let me know what you think, thanks!

**Comment by CoreyD97** [comment]
Sorry for only just replying to this, I've finally had some days to work on Logger this week.
I've started adding this feature, and will be including it in the upcoming release.

Thanks again for another awesome suggestion!

**Comment by Shaddy** [comment]
@CoreyD97 late is always better than never. I really appreciate your work, thanks for this :)

**Comment by CoreyD97** [comment]
Glad you enjoy the extension! I've got a few changes queued up that I'll probably push in a pre release tomorrow if you want to give them a go? 😁

**Comment by Shaddy** [comment]
@CoreyD97 I love it! Stepper is also awesome, but this is a must. 

I'll be monitoring your commits so I can test new features :), is it possible you're referring to the initial prototype for filter aliases :P?

**Comment by CoreyD97** [comment]
I am indeed referring to filter aliases, it's been a fun feature to implement and I've loved using it during testing!

**Comment by Shaddy** [comment]
Woooowwww, can't wait to try it!! Yeah, that feature seemed kinda a challenge to me, there were some issues to deal with, looking forward to testing it! thanks!

**Comment by Shaddy** [comment]
@CoreyD97 I've tested the `dev` branch and man, ITS AWESOME!!!

Thanks for that. I'll be testing everything these days, as of now seems your changes make everything way smoothier, is so responsive but I still to test everything further. Aliases are a game changer.

I'd love to see some day an aliases server or so to collaborate all together with useful patterns. Something similar to what the Burp Extension Marketplace is, but with aliases/regexes. Dreaming is free xD

**Comment by CoreyD97** [comment]
Its funny you mention that! My original idea for the filter library pulled a list of available filters from a file in this repo with the ability for users to contribute them, but I didn't get any contributions in the ~18 months it was available so I rewrote the library for this feature instead :)

**Comment by Shaddy** [comment]
My apologies if you feel the contribution thing is frustrating because of the past :(

IMO from my past experience the usability wasn't enough good because of the tiny errors, rendering stuff etc, misclick on regex filter (/whatever) without the last / freezed the entire burp UI. You know this because you've been working hard and now the feeling is totally different. It works very smooth and is super usable. The main troubble with Burp is when any extension breaks or freezes the UI/engine.

The extensions market still has that version, it's about to wait for people to have the right expectations. This is a #1 tool in Burp and should be in the core some day (same with Stepper)

Having a good library regexes is way better than the typical "active scan" stupid regexes. At the end you want to look at the requests, and play with them. Not just having red flags saying hey, you have money here.

I will be creating a good set of regexes going forward, I'll take time, but it's totally worth it.

Thanks for your active contributions to the community :)

**Comment by CoreyD97** [comment]
Not at all, your ideas are great and I'm glad you mentioned it.

Once enough people have tested this release and confirmed its stable I'm hoping to release it to the Bapp store as the current version is extremely outdated. :)
