### ISSUE TITLE
[Feature] Allow aliases for predefined library filters.

### ISSUE THREAD

**Issue by Shaddy** [nccgroup/LoggerPlusPlus#76]
# Implementing filter aliases 

## Description 

Using library filters as aliases would lead to more human-readable filters. By referencing it with a prefix such as `FL#` we could build complex filters with a simpler syntax.

Let me go through examples from simplest to complex.

### Basic Filters

The point with these filters is the possibility to have `[a-zA-Z0-9_]` syntax with aliases.

Anytime you use a `fs#post_success` or `fs#nonemtpy` aliases they should act as the filter itself.

|          title           |    alias    |                       filter                        |
|:------------------------:|:------------:|:--------------------------------------------------:|
| Post with a valid status |   Post200    | `request.method == post && response.status == 200` |
|            -             | PostSuccess  |                         -                          |
|            -             | post_success |                         -                          |
|   Non-Empty responses    |   nonempty   |               `response.length > 0`                |
|     Empty responses      |    empty     |               `response.length == 0`               |

In my opinion, the match for these tags should be case insensitive.

### Medium Filter

It would be great, also, to be able to recursively reference a filter, by using the same `#` special char or the one that commonly refers to a variable `$` e. g.

|        title        |    alias     |             filter              |
|:-------------------:|:------------:|:-------------------------------:|
|   Non empty post    | NonEmptyPost |   `fs$nonempty && fs$postsuccess`    |

- `fs#nonemptypost` would have the same effect.

### Advanced Filters

But what will give this feature the most powerful way of expressing filters, is to have regex groups syntax representing the alias itself.

|     title     |     alias     |                    filter                    |
|:-------------:|:-------------:|:--------------------------------------------:|
| CacheControl  | cachecontrol  |           `/Cache-Control: (w+)$/`           |
| ResponseCache | responsecache | `response.headers == /Cache-Control: (w+)$/` |
| CacheHeaders  | cachecontrol  |      `response.headers == /(Cache-Control\|Pragma): (w+)$/`       |
|   UserAgent   |   useragent   |      `response.headers == /User-Agent: ([a-zA-Z0-9,/(]+)$/`      |

This will open filters like.

- `fs#cachecontrol in ["public", "private", "no-store"]`

- `fs#useragent == /Chrome/`

- `fs#responsecache` (As a particular example, even tho no expression follows the captured group special alias, it should be used as a simple matcher of the expression itself

## Remarks

They should be able to use as colorizing expressions as well.

## Final

I am not sure of the complexity so that's why I have tried to split them into acquirable goals, would love to hear your thoughts on this!

Thanks!

**Comment by CoreyD97** [comment]
This suggestion is awesome. Thanks for writing it up in such detail too, I've got a good understanding of what you're asking and all aspects should be achievable. 

Basic Filters: 
Not a problem, this should be quite easy to implement.

Medium/Recursive Filters: 
Also shouldn't be too hard. Will need to make sure we protect against users accidentally making recursive loops.

Advanced Filters: 
This will be a little trickier, but still possible. I'll have to think about how this will be implemented in a bit more detail once the other elements are complete.

Thanks again for the awesome suggestion!

**Comment by CoreyD97** [comment]
The only issue I see currently is down to the handling of modified / deleted aliases which are in use within other filters.

When setting a new Log/Color Filter, this won't be an issue as the filter can be parsed and any aliases used expanded at that point. 
However, if an alias is changed, all users of filters must reevaluate their values to determine if they must refresh.

This is all possible, but might take a few attempts to get right 😊

**Comment by Shaddy** [comment]
> Also shouldn't be too hard. Will need to make sure we protect against users accidentally making recursive loops.

That's a good point.

> However, if an alias is changed, all users of filters must reevaluate their values to determine if they must refresh.

Exactly, it is the only thing to take care of, if any mutation of an "offensive" alias (changed, removed) is made they should be invalidated until a new reevaluation is done. 

Also, the same logic should apply to point #1, anyone that changes an alias could recursively reference itself and hang the extension.

Seems that you have the right steps in your mind! This could be awesome 😄

**Comment by CoreyD97** [comment]
I've made the initial implementation of this feature in the development branch, with a couple of known issues at the moment.

I have added rudimentary recursion check which gets carried out when filters are defined and later used in log filters and color filters, and when the filters in the filter library are changed the changes do not propagate to log filters or color filters until they are refreshed manually.
