### ISSUE TITLE
ElasticSearch - Support for 7.X.X & Remote Instances

### ISSUE THREAD

**Issue by ACC1715** [nccgroup/LoggerPlusPlus#79]
Hello!

It would be great if support for newer versions of ElasticSearch could be added, and possibly the ability to use remote instances of ElasticSearch?

The biggest issue I have come up against with remote instances is that there is currently no functionality to add custom headers (like an auth header) so the only way to use them would be through an unauthenticated setup of ElasticSearch :(

Thanks

**Comment by CoreyD97** [comment]
Thanks for the suggestion, sorry its taken a while to actually get around to looking at it.
I've just rewritten the elastic search integration so would like to implement this also.

Does the authentication mechanism below suit your needs?
elastic.co/guide/en/elasticsearch/client/java-rest/current/_basic_authentication.html

**Comment by CoreyD97** [comment]
Implemented! https://github.com/nccgroup/LoggerPlusPlus/commit/46fca586c3c679f137d53733374cdf84d56a16ee
