### ISSUE TITLE
Logger++ 3.12 doesn't upload data to elastic search

### ISSUE THREAD

**Issue by arbazkiraak** [nccgroup/LoggerPlusPlus#80]
> I'm running the latest version of the elastic server on localhost, logger++ created an index but requests are not getting uploaded.

Logger ++ 3.12

**Comment by CoreyD97** [comment]
As of commit 04e3b9a1, the elasticsearch integration has been rewritten and tested so I'll close this issue. If you have any issues after this feel free to reopen this issue.
