### ISSUE TITLE
Add the option to export all requests as json

### ISSUE THREAD

**Issue by tkisason** [nccgroup/LoggerPlusPlus#81]
Hello,

I was wondering how hard would it be to patch this extension so it can dump all requests in JSON form, the reason is simple, then we can query the entire dump with a bunch of jq scripts and potentially find more interesting stuff during our audits. 

Sincerely,
Tonimir

**Comment by tkisason** [comment]
:scream: Awesome. Thanks!

**Comment by CoreyD97** [comment]
Sorry its taken a while to get implemented :)
