### ISSUE TITLE
Filter Works / Doesn't Work Based on Order of Search Fields

### ISSUE THREAD

**Issue by ossie-git** [nccgroup/LoggerPlusPlus#83]
I am using the latest version (3.07)

For some reason, the first field that I use determines the filter output although it shouldn't.  For example:

```
PATH == "/favicon.ico" && HOST == "http://httpbin.org"
```

![works](https://user-images.githubusercontent.com/25382296/71329737-9a1d3800-257c-11ea-91bd-f5ae1ba661c2.png)

now if I just switch the order of the search items

```
HOST == "http://httpbin.org" && PATH == "/favicon.ico"
```

the filter no longer returns any results

![noresult](https://user-images.githubusercontent.com/25382296/71329749-a903ea80-257c-11ea-98f2-7282422af3ea.png)

**Comment by CoreyD97** [comment]
Hey!
Sorry for the slow response, I took some time off over Christmas and didn't see this issue come in.
I've completely rewritten the filter parser and evaluation logic for the next major release of Logger++ so this shouldn't be an issue in future. 

Thanks,
Corey

**Comment by yam23** [comment]
do you have any estimate when it will be release? 

Thanks,
Anis

**Comment by CoreyD97** [comment]
Ive got some bugs to polish off first but hopefully I'll have a pre release in the next few weeks with the new filter implementation.
