### ISSUE TITLE
Logger++ does not show the correct delay between request and response

### ISSUE THREAD

**Issue by TurpalGadamauri** [nccgroup/LoggerPlusPlus#94]
**Description:**
The logger++ plugin does not show the correct delay between a request and response when a request is made from the repeater tab. I have tested this with a request smuggling attack on the portswigger labs. I see this issue also with normal requests made from the repeater tab suggesting it is not linked to the attack.

https://portswigger.net/web-security/request-smuggling/lab-basic-cl-te

**Steps To Reproduce:**

1. send a POST request from the repeater tab containing the following headers and body
```
Transfer-Encoding: chunked
Content-Length: 4

1
Z
Q
```

2. compare the time from the repeater tab (lower right corner) and the time from logger++ (response delay).

alternatively send any request from the repeater tab and do step 2

**Expected behavior:**

the delay shown in the repeater tab should equal the delay shown in the logger++ plugin.

**Screenshots:**

normal request
![image](https://user-images.githubusercontent.com/24373956/80697081-b99f1100-8ad8-11ea-887e-8c7e104f3756.png)

request smuggling attack
![image](https://user-images.githubusercontent.com/24373956/80697426-38944980-8ad9-11ea-8f93-f53ea4a6175d.png)

logger++
![image](https://user-images.githubusercontent.com/24373956/80697401-2f0ae180-8ad9-11ea-9e6e-f5d15cea9e9e.png)

**Version:**
Burp Suite community edition v2020.01
Logger++ version 3.07

**Comment by CoreyD97** [comment]
Hey, thanks for submitting this.
Could you try updating to the latest release of Logger++ and see if this is more accurate?

**Comment by CoreyD97** [comment]
Its also worth noting that request times are as received by the extension, if you have any extensions which perform operations during the processHttpMessage method this may effect the RTT time.

**Comment by TurpalGadamauri** [comment]
Hey sorry to have bothered. I updated Burp Suite and Logger++ to the latest versions and the delays are pretty accurate now. 

Thanks for making this great plugin!
