### ISSUE TITLE
Save the CSV/JSON Exporter fields preferences

### ISSUE THREAD

**Issue by maximilianosoler** [nccgroup/LoggerPlusPlus#96]
**Feature description:**
First of all thank you for this great extension!
I would like to have an option to save the preferences for the fields selected for the CSV/JSON Exporter.

**Scenario example:**
For example, it's common to use the same fields to export the files CSV and JSON.
Every time we need to export, it's necessary to remember which filters should I select and then export them. Will be great to have it predefined, when Burp Suite starts.

Maybe two buttons: **Default** (Saved/Predefined) and **Select All**

Thanks again and stay safe,
Maxi

**Comment by ynsy** [comment]
This will be great preference and save my time.

**Comment by CoreyD97** [comment]
Hey! At the moment the previously selected fields should be used as the defaults, but I will add the ability to save/load as a preset instead of using the last used selection, as well as the select all button.

Thanks for the suggestion!

**Comment by ynsy** [comment]
Hello @CoreyD97 , actually it doesnt work as you said. I select some fields and when i restart the burp, it is resetting and i should select them again.

**Comment by CoreyD97** [comment]
Ah, sorry about that. I had implemented it but maybe its not loading them properly. I'll look into this for you!

**Comment by maximilianosoler** [comment]
@CoreyD97 thanks a lot for your quick response.
Let us know if we can help you and try it.

Stay safe,
Maxi

**Comment by CoreyD97** [comment]
Hey! Just implemented this now, you can get the jar from here to test. Let me know if you have any issues!
https://github.com/nccgroup/LoggerPlusPlus/actions/runs/104679601
Thanks!

**Comment by maximilianosoler** [comment]
Hi @CoreyD97 , thank you so much for sharing it!
The improvements are great!
Just one thing, after selecting and creating a **Filter** (i.e. _test 001 - logger_), when I open again Burp Suite, the OK Button is grey, so it's necessary to (un)click some filter to active the **OK** to export the file.

See the following example:
![image](https://user-images.githubusercontent.com/40498492/81945497-91350d80-95d4-11ea-9f7c-2d926f80e08a.png)
 
Thank you again and regards,
Maxi Soler

**Comment by CoreyD97** [comment]
Thanks for that! I've just pushed a fix for that bug :)

**Comment by maximilianosoler** [comment]
Cool, let me know I can help to test it.

**Comment by CoreyD97** [comment]
Thanks! The jar can be downloaded here: https://github.com/nccgroup/LoggerPlusPlus/actions/runs/104742254
