### ISSUE TITLE
Elasticsearch Exporter auto start

### ISSUE THREAD

**Issue by Regala** [nccgroup/LoggerPlusPlus#99]
**Feature description:**
Logger++ now supports sending to Elasticsearch. All the configurations are saved and loaded again when Burp / the extension reloads. However, you have to manually start the Elasticsearch Exporter by clicking the button.

It would be awesome if this could automatically start every time (if possible, making it a user option rather than project option).

**Scenario example:**

- In project ACME after loading the extension and configuring the explorer, once we activate it, it will persist when we reload Burp / extension.

or/and

- Simple checkbox to specify if we want to autostart (similar to the Logger++ status) 

Thanks!

**Comment by CoreyD97** [comment]
"if possible, making it a user option rather than project option"

Sorry I'm not quite sure what you mean here. All of Logger++'s options are user/global options at the minute. Did you want this option to be per-project instead? Did you accidentally switch user/project around or am I reading this wrong? :smile: 
Either way, both are possible, just let me know which would be more suitable!

**Comment by Regala** [comment]
Ahah exactly, I meant being global!

**Comment by Regala** [comment]
Hi @CoreyD97! I know you prob super busy but quick bump hoping someone can pick this 😄  Cheers!

**Comment by CoreyD97** [comment]
Hey!

Really sorry, I have implemented this already but am waiting to do a few more issues before the full release. In the meantime though, I have configured GitHub to produce a new jar for every commit I push, so there's a work in progress build you can grab from here: https://github.com/nccgroup/LoggerPlusPlus/suites/868315815/artifacts/10065221

Let me know if its okay for you!

**Comment by Regala** [comment]
That's brilliant! I'll test it out, thanks!!

**Comment by Regala** [comment]
Hey @CoreyD97 ! So I ran the last build (https://github.com/nccgroup/LoggerPlusPlus/suites/868315815/artifacts/10065221) and can see the autostart options! Unfortunately, it doesn't seem to be working for me:

- For the same project, with the options:
![elastic_config](https://user-images.githubusercontent.com/1380527/87432927-99172b00-c5e0-11ea-9217-02c8f0416dc9.png)
- And with the exporter service running if I quit Burp and then open the same project:
![explorer](https://user-images.githubusercontent.com/1380527/87433036-bba94400-c5e0-11ea-9e91-cfb1457ea732.png)
The options are set but the service is not auto started.

The log shows that the options are set to `True` so it should be working:
![elastic_log](https://user-images.githubusercontent.com/1380527/87433126-dbd90300-c5e0-11ea-8c86-4f77daced5a6.png)

I thought it could be a UI mismatch (service running but the button not being clicked / showed) - but I don't think so, don't see any uploads happening. Running Burp v2020.4. Any thoughts? Am I doing something wrong?

**Comment by Regala** [comment]
(unrelated, are filters applied to the elastic exporter service too? e.g say, I don't want .png or .jpeg responses to be sent to exporter)

**Comment by CoreyD97** [comment]
Hmm, that's odd. I had tested this and confirmed it was working! 
If you manually start it, can you see the requests uploaded then? Just to rule out a config issue?

+ Not currently, but that is something I could do pretty easily :)

**Comment by Regala** [comment]
Jep it works after if I manually start it! I'll try setting up a new project just to rule out any shenanigans too

**Comment by Regala** [comment]
Yep same thing I'm afraid :/ 

Regarding the filters - that would be awesome! Sending in ALL of the responses is pretty chaotic; but if we could ignore by content type or extension and upload all the others then it would be 🙏

**Comment by CoreyD97** [comment]
Thanks for confirming that, I'll take a look at it soon!
I'm on an assignment currently but I should have some time to look into it later this week, and I'll look at implementing the filters too. https://github.com/nccgroup/LoggerPlusPlus/issues/107

**Comment by Regala** [comment]
Awesome cheers! Lmk if I can help!

**Comment by CoreyD97** [comment]
@Regala - I've done some work on the ElasticSearch integration recently. Can you confirm if you still have this issue with the latest commit? https://github.com/nccgroup/LoggerPlusPlus/suites/2654634134/artifacts/58378254

**Comment by Regala** [comment]
@CoreyD97 I tried to load it and I'm getting this UI error:
![error_1](https://user-images.githubusercontent.com/1380527/118114257-3f89b380-b3df-11eb-9cea-0485371ce790.png)

I've tried to build it locally later with `./gradlew build` and got no errors, but still the same problem loading it 🤔

Running it on Burp v2021.4.3 on Mac OSX

**Comment by Regala** [comment]
Extension is actually loaded but yeah the window pane is not available :P

**Comment by Regala** [comment]
I think I got it, created a new temporary project and it works; so maybe the elastic exporter tried to boot up, got some error and prevented the rest to work.

**Comment by CoreyD97** [comment]
Hmm, looks like that issue is unrelated to ElasticSearch and just a general error. I'll look into it and get back to you. Thanks for your help!

**Comment by CoreyD97** [comment]
This issue was caused by the Elastic Exporter trying to display an alert before the UI had been added. This has been fixed so all should work as expected now!
